//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("SATModel", "FK_Courses_CourseStatus1", "SATCourseStatuses", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SAT1.SATCourseStatus), "SATCourses", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SAT1.SATCours), true)]
[assembly: EdmRelationshipAttribute("SATModel", "FK_ScheduledClasses_Courses", "SATCourses", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SAT1.SATCours), "SATScheduledClasses", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SAT1.SATScheduledClass), true)]
[assembly: EdmRelationshipAttribute("SATModel", "FK_Enrollments_ScheduledClasses", "SATScheduledClasses", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SAT1.SATScheduledClass), "SATEnrollments", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SAT1.SATEnrollment), true)]
[assembly: EdmRelationshipAttribute("SATModel", "FK_Enrollments_Students", "SATStudents", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SAT1.SATStudent), "SATEnrollments", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SAT1.SATEnrollment), true)]
[assembly: EdmRelationshipAttribute("SATModel", "FK_ScheduledClasses_ScheduledClassStatus1", "SATScheduledClassStatuses", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SAT1.SATScheduledClassStatus), "SATScheduledClasses", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SAT1.SATScheduledClass), true)]
[assembly: EdmRelationshipAttribute("SATModel", "FK_Students_StudentStatus", "SATStudentStatuses", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SAT1.SATStudentStatus), "SATStudents", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SAT1.SATStudent), true)]

#endregion

namespace SAT1
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class SATEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new SATEntities object using the connection string found in the 'SATEntities' section of the application configuration file.
        /// </summary>
        public SATEntities() : base("name=SATEntities", "SATEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SATEntities object.
        /// </summary>
        public SATEntities(string connectionString) : base(connectionString, "SATEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SATEntities object.
        /// </summary>
        public SATEntities(EntityConnection connection) : base(connection, "SATEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SATCours> SATCourses
        {
            get
            {
                if ((_SATCourses == null))
                {
                    _SATCourses = base.CreateObjectSet<SATCours>("SATCourses");
                }
                return _SATCourses;
            }
        }
        private ObjectSet<SATCours> _SATCourses;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SATCourseStatus> SATCourseStatuses
        {
            get
            {
                if ((_SATCourseStatuses == null))
                {
                    _SATCourseStatuses = base.CreateObjectSet<SATCourseStatus>("SATCourseStatuses");
                }
                return _SATCourseStatuses;
            }
        }
        private ObjectSet<SATCourseStatus> _SATCourseStatuses;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SATEnrollment> SATEnrollments
        {
            get
            {
                if ((_SATEnrollments == null))
                {
                    _SATEnrollments = base.CreateObjectSet<SATEnrollment>("SATEnrollments");
                }
                return _SATEnrollments;
            }
        }
        private ObjectSet<SATEnrollment> _SATEnrollments;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SATScheduledClass> SATScheduledClasses
        {
            get
            {
                if ((_SATScheduledClasses == null))
                {
                    _SATScheduledClasses = base.CreateObjectSet<SATScheduledClass>("SATScheduledClasses");
                }
                return _SATScheduledClasses;
            }
        }
        private ObjectSet<SATScheduledClass> _SATScheduledClasses;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SATScheduledClassStatus> SATScheduledClassStatuses
        {
            get
            {
                if ((_SATScheduledClassStatuses == null))
                {
                    _SATScheduledClassStatuses = base.CreateObjectSet<SATScheduledClassStatus>("SATScheduledClassStatuses");
                }
                return _SATScheduledClassStatuses;
            }
        }
        private ObjectSet<SATScheduledClassStatus> _SATScheduledClassStatuses;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SATStudent> SATStudents
        {
            get
            {
                if ((_SATStudents == null))
                {
                    _SATStudents = base.CreateObjectSet<SATStudent>("SATStudents");
                }
                return _SATStudents;
            }
        }
        private ObjectSet<SATStudent> _SATStudents;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SATStudentStatus> SATStudentStatuses
        {
            get
            {
                if ((_SATStudentStatuses == null))
                {
                    _SATStudentStatuses = base.CreateObjectSet<SATStudentStatus>("SATStudentStatuses");
                }
                return _SATStudentStatuses;
            }
        }
        private ObjectSet<SATStudentStatus> _SATStudentStatuses;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SATCourses EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSATCourses(SATCours sATCours)
        {
            base.AddObject("SATCourses", sATCours);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SATCourseStatuses EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSATCourseStatuses(SATCourseStatus sATCourseStatus)
        {
            base.AddObject("SATCourseStatuses", sATCourseStatus);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SATEnrollments EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSATEnrollments(SATEnrollment sATEnrollment)
        {
            base.AddObject("SATEnrollments", sATEnrollment);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SATScheduledClasses EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSATScheduledClasses(SATScheduledClass sATScheduledClass)
        {
            base.AddObject("SATScheduledClasses", sATScheduledClass);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SATScheduledClassStatuses EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSATScheduledClassStatuses(SATScheduledClassStatus sATScheduledClassStatus)
        {
            base.AddObject("SATScheduledClassStatuses", sATScheduledClassStatus);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SATStudents EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSATStudents(SATStudent sATStudent)
        {
            base.AddObject("SATStudents", sATStudent);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SATStudentStatuses EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSATStudentStatuses(SATStudentStatus sATStudentStatus)
        {
            base.AddObject("SATStudentStatuses", sATStudentStatus);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SATModel", Name="SATCours")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SATCours : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SATCours object.
        /// </summary>
        /// <param name="courseId">Initial value of the courseId property.</param>
        /// <param name="courseName">Initial value of the courseName property.</param>
        /// <param name="statusId">Initial value of the statusId property.</param>
        public static SATCours CreateSATCours(global::System.Int32 courseId, global::System.String courseName, global::System.Int32 statusId)
        {
            SATCours sATCours = new SATCours();
            sATCours.courseId = courseId;
            sATCours.courseName = courseName;
            sATCours.statusId = statusId;
            return sATCours;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 courseId
        {
            get
            {
                return _courseId;
            }
            set
            {
                if (_courseId != value)
                {
                    OncourseIdChanging(value);
                    ReportPropertyChanging("courseId");
                    _courseId = StructuralObject.SetValidValue(value, "courseId");
                    ReportPropertyChanged("courseId");
                    OncourseIdChanged();
                }
            }
        }
        private global::System.Int32 _courseId;
        partial void OncourseIdChanging(global::System.Int32 value);
        partial void OncourseIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String courseName
        {
            get
            {
                return _courseName;
            }
            set
            {
                OncourseNameChanging(value);
                ReportPropertyChanging("courseName");
                _courseName = StructuralObject.SetValidValue(value, false, "courseName");
                ReportPropertyChanged("courseName");
                OncourseNameChanged();
            }
        }
        private global::System.String _courseName;
        partial void OncourseNameChanging(global::System.String value);
        partial void OncourseNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String courseDescription
        {
            get
            {
                return _courseDescription;
            }
            set
            {
                OncourseDescriptionChanging(value);
                ReportPropertyChanging("courseDescription");
                _courseDescription = StructuralObject.SetValidValue(value, true, "courseDescription");
                ReportPropertyChanged("courseDescription");
                OncourseDescriptionChanged();
            }
        }
        private global::System.String _courseDescription;
        partial void OncourseDescriptionChanging(global::System.String value);
        partial void OncourseDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String department
        {
            get
            {
                return _department;
            }
            set
            {
                OndepartmentChanging(value);
                ReportPropertyChanging("department");
                _department = StructuralObject.SetValidValue(value, true, "department");
                ReportPropertyChanged("department");
                OndepartmentChanged();
            }
        }
        private global::System.String _department;
        partial void OndepartmentChanging(global::System.String value);
        partial void OndepartmentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String curriculum
        {
            get
            {
                return _curriculum;
            }
            set
            {
                OncurriculumChanging(value);
                ReportPropertyChanging("curriculum");
                _curriculum = StructuralObject.SetValidValue(value, true, "curriculum");
                ReportPropertyChanged("curriculum");
                OncurriculumChanged();
            }
        }
        private global::System.String _curriculum;
        partial void OncurriculumChanging(global::System.String value);
        partial void OncurriculumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String notes
        {
            get
            {
                return _notes;
            }
            set
            {
                OnnotesChanging(value);
                ReportPropertyChanging("notes");
                _notes = StructuralObject.SetValidValue(value, true, "notes");
                ReportPropertyChanged("notes");
                OnnotesChanged();
            }
        }
        private global::System.String _notes;
        partial void OnnotesChanging(global::System.String value);
        partial void OnnotesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 statusId
        {
            get
            {
                return _statusId;
            }
            set
            {
                OnstatusIdChanging(value);
                ReportPropertyChanging("statusId");
                _statusId = StructuralObject.SetValidValue(value, "statusId");
                ReportPropertyChanged("statusId");
                OnstatusIdChanged();
            }
        }
        private global::System.Int32 _statusId;
        partial void OnstatusIdChanging(global::System.Int32 value);
        partial void OnstatusIdChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SATModel", "FK_Courses_CourseStatus1", "SATCourseStatuses")]
        public SATCourseStatus SATCourseStatus
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SATCourseStatus>("SATModel.FK_Courses_CourseStatus1", "SATCourseStatuses").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SATCourseStatus>("SATModel.FK_Courses_CourseStatus1", "SATCourseStatuses").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<SATCourseStatus> SATCourseStatusReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SATCourseStatus>("SATModel.FK_Courses_CourseStatus1", "SATCourseStatuses");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<SATCourseStatus>("SATModel.FK_Courses_CourseStatus1", "SATCourseStatuses", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SATModel", "FK_ScheduledClasses_Courses", "SATScheduledClasses")]
        public EntityCollection<SATScheduledClass> SATScheduledClasses
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SATScheduledClass>("SATModel.FK_ScheduledClasses_Courses", "SATScheduledClasses");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SATScheduledClass>("SATModel.FK_ScheduledClasses_Courses", "SATScheduledClasses", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SATModel", Name="SATCourseStatus")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SATCourseStatus : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SATCourseStatus object.
        /// </summary>
        /// <param name="cSID">Initial value of the CSID property.</param>
        /// <param name="cSName">Initial value of the CSName property.</param>
        public static SATCourseStatus CreateSATCourseStatus(global::System.Int32 cSID, global::System.String cSName)
        {
            SATCourseStatus sATCourseStatus = new SATCourseStatus();
            sATCourseStatus.CSID = cSID;
            sATCourseStatus.CSName = cSName;
            return sATCourseStatus;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CSID
        {
            get
            {
                return _CSID;
            }
            set
            {
                if (_CSID != value)
                {
                    OnCSIDChanging(value);
                    ReportPropertyChanging("CSID");
                    _CSID = StructuralObject.SetValidValue(value, "CSID");
                    ReportPropertyChanged("CSID");
                    OnCSIDChanged();
                }
            }
        }
        private global::System.Int32 _CSID;
        partial void OnCSIDChanging(global::System.Int32 value);
        partial void OnCSIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CSName
        {
            get
            {
                return _CSName;
            }
            set
            {
                OnCSNameChanging(value);
                ReportPropertyChanging("CSName");
                _CSName = StructuralObject.SetValidValue(value, false, "CSName");
                ReportPropertyChanged("CSName");
                OnCSNameChanged();
            }
        }
        private global::System.String _CSName;
        partial void OnCSNameChanging(global::System.String value);
        partial void OnCSNameChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SATModel", "FK_Courses_CourseStatus1", "SATCourses")]
        public EntityCollection<SATCours> SATCourses
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SATCours>("SATModel.FK_Courses_CourseStatus1", "SATCourses");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SATCours>("SATModel.FK_Courses_CourseStatus1", "SATCourses", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SATModel", Name="SATEnrollment")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SATEnrollment : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SATEnrollment object.
        /// </summary>
        /// <param name="enrollmentId">Initial value of the enrollmentId property.</param>
        /// <param name="scheduledClassId">Initial value of the scheduledClassId property.</param>
        /// <param name="studentId">Initial value of the studentId property.</param>
        /// <param name="enrollmentDate">Initial value of the enrollmentDate property.</param>
        public static SATEnrollment CreateSATEnrollment(global::System.Int32 enrollmentId, global::System.Int32 scheduledClassId, global::System.Int32 studentId, global::System.DateTime enrollmentDate)
        {
            SATEnrollment sATEnrollment = new SATEnrollment();
            sATEnrollment.enrollmentId = enrollmentId;
            sATEnrollment.scheduledClassId = scheduledClassId;
            sATEnrollment.studentId = studentId;
            sATEnrollment.enrollmentDate = enrollmentDate;
            return sATEnrollment;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 enrollmentId
        {
            get
            {
                return _enrollmentId;
            }
            set
            {
                if (_enrollmentId != value)
                {
                    OnenrollmentIdChanging(value);
                    ReportPropertyChanging("enrollmentId");
                    _enrollmentId = StructuralObject.SetValidValue(value, "enrollmentId");
                    ReportPropertyChanged("enrollmentId");
                    OnenrollmentIdChanged();
                }
            }
        }
        private global::System.Int32 _enrollmentId;
        partial void OnenrollmentIdChanging(global::System.Int32 value);
        partial void OnenrollmentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 scheduledClassId
        {
            get
            {
                return _scheduledClassId;
            }
            set
            {
                OnscheduledClassIdChanging(value);
                ReportPropertyChanging("scheduledClassId");
                _scheduledClassId = StructuralObject.SetValidValue(value, "scheduledClassId");
                ReportPropertyChanged("scheduledClassId");
                OnscheduledClassIdChanged();
            }
        }
        private global::System.Int32 _scheduledClassId;
        partial void OnscheduledClassIdChanging(global::System.Int32 value);
        partial void OnscheduledClassIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 studentId
        {
            get
            {
                return _studentId;
            }
            set
            {
                OnstudentIdChanging(value);
                ReportPropertyChanging("studentId");
                _studentId = StructuralObject.SetValidValue(value, "studentId");
                ReportPropertyChanged("studentId");
                OnstudentIdChanged();
            }
        }
        private global::System.Int32 _studentId;
        partial void OnstudentIdChanging(global::System.Int32 value);
        partial void OnstudentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime enrollmentDate
        {
            get
            {
                return _enrollmentDate;
            }
            set
            {
                OnenrollmentDateChanging(value);
                ReportPropertyChanging("enrollmentDate");
                _enrollmentDate = StructuralObject.SetValidValue(value, "enrollmentDate");
                ReportPropertyChanged("enrollmentDate");
                OnenrollmentDateChanged();
            }
        }
        private global::System.DateTime _enrollmentDate;
        partial void OnenrollmentDateChanging(global::System.DateTime value);
        partial void OnenrollmentDateChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SATModel", "FK_Enrollments_ScheduledClasses", "SATScheduledClasses")]
        public SATScheduledClass SATScheduledClass
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SATScheduledClass>("SATModel.FK_Enrollments_ScheduledClasses", "SATScheduledClasses").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SATScheduledClass>("SATModel.FK_Enrollments_ScheduledClasses", "SATScheduledClasses").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<SATScheduledClass> SATScheduledClassReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SATScheduledClass>("SATModel.FK_Enrollments_ScheduledClasses", "SATScheduledClasses");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<SATScheduledClass>("SATModel.FK_Enrollments_ScheduledClasses", "SATScheduledClasses", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SATModel", "FK_Enrollments_Students", "SATStudents")]
        public SATStudent SATStudent
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SATStudent>("SATModel.FK_Enrollments_Students", "SATStudents").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SATStudent>("SATModel.FK_Enrollments_Students", "SATStudents").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<SATStudent> SATStudentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SATStudent>("SATModel.FK_Enrollments_Students", "SATStudents");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<SATStudent>("SATModel.FK_Enrollments_Students", "SATStudents", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SATModel", Name="SATScheduledClass")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SATScheduledClass : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SATScheduledClass object.
        /// </summary>
        /// <param name="scheduledClassId">Initial value of the scheduledClassId property.</param>
        /// <param name="courseId">Initial value of the courseId property.</param>
        /// <param name="statusId">Initial value of the statusId property.</param>
        public static SATScheduledClass CreateSATScheduledClass(global::System.Int32 scheduledClassId, global::System.Int32 courseId, global::System.Int32 statusId)
        {
            SATScheduledClass sATScheduledClass = new SATScheduledClass();
            sATScheduledClass.scheduledClassId = scheduledClassId;
            sATScheduledClass.courseId = courseId;
            sATScheduledClass.statusId = statusId;
            return sATScheduledClass;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 scheduledClassId
        {
            get
            {
                return _scheduledClassId;
            }
            set
            {
                if (_scheduledClassId != value)
                {
                    OnscheduledClassIdChanging(value);
                    ReportPropertyChanging("scheduledClassId");
                    _scheduledClassId = StructuralObject.SetValidValue(value, "scheduledClassId");
                    ReportPropertyChanged("scheduledClassId");
                    OnscheduledClassIdChanged();
                }
            }
        }
        private global::System.Int32 _scheduledClassId;
        partial void OnscheduledClassIdChanging(global::System.Int32 value);
        partial void OnscheduledClassIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 courseId
        {
            get
            {
                return _courseId;
            }
            set
            {
                OncourseIdChanging(value);
                ReportPropertyChanging("courseId");
                _courseId = StructuralObject.SetValidValue(value, "courseId");
                ReportPropertyChanged("courseId");
                OncourseIdChanged();
            }
        }
        private global::System.Int32 _courseId;
        partial void OncourseIdChanging(global::System.Int32 value);
        partial void OncourseIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> startDate
        {
            get
            {
                return _startDate;
            }
            set
            {
                OnstartDateChanging(value);
                ReportPropertyChanging("startDate");
                _startDate = StructuralObject.SetValidValue(value, "startDate");
                ReportPropertyChanged("startDate");
                OnstartDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _startDate;
        partial void OnstartDateChanging(Nullable<global::System.DateTime> value);
        partial void OnstartDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> endDate
        {
            get
            {
                return _endDate;
            }
            set
            {
                OnendDateChanging(value);
                ReportPropertyChanging("endDate");
                _endDate = StructuralObject.SetValidValue(value, "endDate");
                ReportPropertyChanged("endDate");
                OnendDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _endDate;
        partial void OnendDateChanging(Nullable<global::System.DateTime> value);
        partial void OnendDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> creditHours
        {
            get
            {
                return _creditHours;
            }
            set
            {
                OncreditHoursChanging(value);
                ReportPropertyChanging("creditHours");
                _creditHours = StructuralObject.SetValidValue(value, "creditHours");
                ReportPropertyChanged("creditHours");
                OncreditHoursChanged();
            }
        }
        private Nullable<global::System.Double> _creditHours;
        partial void OncreditHoursChanging(Nullable<global::System.Double> value);
        partial void OncreditHoursChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String instructorName
        {
            get
            {
                return _instructorName;
            }
            set
            {
                OninstructorNameChanging(value);
                ReportPropertyChanging("instructorName");
                _instructorName = StructuralObject.SetValidValue(value, true, "instructorName");
                ReportPropertyChanged("instructorName");
                OninstructorNameChanged();
            }
        }
        private global::System.String _instructorName;
        partial void OninstructorNameChanging(global::System.String value);
        partial void OninstructorNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String location
        {
            get
            {
                return _location;
            }
            set
            {
                OnlocationChanging(value);
                ReportPropertyChanging("location");
                _location = StructuralObject.SetValidValue(value, true, "location");
                ReportPropertyChanged("location");
                OnlocationChanged();
            }
        }
        private global::System.String _location;
        partial void OnlocationChanging(global::System.String value);
        partial void OnlocationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 statusId
        {
            get
            {
                return _statusId;
            }
            set
            {
                OnstatusIdChanging(value);
                ReportPropertyChanging("statusId");
                _statusId = StructuralObject.SetValidValue(value, "statusId");
                ReportPropertyChanged("statusId");
                OnstatusIdChanged();
            }
        }
        private global::System.Int32 _statusId;
        partial void OnstatusIdChanging(global::System.Int32 value);
        partial void OnstatusIdChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SATModel", "FK_ScheduledClasses_Courses", "SATCourses")]
        public SATCours SATCours
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SATCours>("SATModel.FK_ScheduledClasses_Courses", "SATCourses").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SATCours>("SATModel.FK_ScheduledClasses_Courses", "SATCourses").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<SATCours> SATCoursReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SATCours>("SATModel.FK_ScheduledClasses_Courses", "SATCourses");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<SATCours>("SATModel.FK_ScheduledClasses_Courses", "SATCourses", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SATModel", "FK_Enrollments_ScheduledClasses", "SATEnrollments")]
        public EntityCollection<SATEnrollment> SATEnrollments
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SATEnrollment>("SATModel.FK_Enrollments_ScheduledClasses", "SATEnrollments");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SATEnrollment>("SATModel.FK_Enrollments_ScheduledClasses", "SATEnrollments", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SATModel", "FK_ScheduledClasses_ScheduledClassStatus1", "SATScheduledClassStatuses")]
        public SATScheduledClassStatus SATScheduledClassStatus
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SATScheduledClassStatus>("SATModel.FK_ScheduledClasses_ScheduledClassStatus1", "SATScheduledClassStatuses").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SATScheduledClassStatus>("SATModel.FK_ScheduledClasses_ScheduledClassStatus1", "SATScheduledClassStatuses").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<SATScheduledClassStatus> SATScheduledClassStatusReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SATScheduledClassStatus>("SATModel.FK_ScheduledClasses_ScheduledClassStatus1", "SATScheduledClassStatuses");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<SATScheduledClassStatus>("SATModel.FK_ScheduledClasses_ScheduledClassStatus1", "SATScheduledClassStatuses", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SATModel", Name="SATScheduledClassStatus")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SATScheduledClassStatus : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SATScheduledClassStatus object.
        /// </summary>
        /// <param name="sCSID">Initial value of the SCSID property.</param>
        /// <param name="sCSName">Initial value of the SCSName property.</param>
        public static SATScheduledClassStatus CreateSATScheduledClassStatus(global::System.Int32 sCSID, global::System.String sCSName)
        {
            SATScheduledClassStatus sATScheduledClassStatus = new SATScheduledClassStatus();
            sATScheduledClassStatus.SCSID = sCSID;
            sATScheduledClassStatus.SCSName = sCSName;
            return sATScheduledClassStatus;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SCSID
        {
            get
            {
                return _SCSID;
            }
            set
            {
                if (_SCSID != value)
                {
                    OnSCSIDChanging(value);
                    ReportPropertyChanging("SCSID");
                    _SCSID = StructuralObject.SetValidValue(value, "SCSID");
                    ReportPropertyChanged("SCSID");
                    OnSCSIDChanged();
                }
            }
        }
        private global::System.Int32 _SCSID;
        partial void OnSCSIDChanging(global::System.Int32 value);
        partial void OnSCSIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SCSName
        {
            get
            {
                return _SCSName;
            }
            set
            {
                OnSCSNameChanging(value);
                ReportPropertyChanging("SCSName");
                _SCSName = StructuralObject.SetValidValue(value, false, "SCSName");
                ReportPropertyChanged("SCSName");
                OnSCSNameChanged();
            }
        }
        private global::System.String _SCSName;
        partial void OnSCSNameChanging(global::System.String value);
        partial void OnSCSNameChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SATModel", "FK_ScheduledClasses_ScheduledClassStatus1", "SATScheduledClasses")]
        public EntityCollection<SATScheduledClass> SATScheduledClasses
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SATScheduledClass>("SATModel.FK_ScheduledClasses_ScheduledClassStatus1", "SATScheduledClasses");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SATScheduledClass>("SATModel.FK_ScheduledClasses_ScheduledClassStatus1", "SATScheduledClasses", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SATModel", Name="SATStudent")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SATStudent : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SATStudent object.
        /// </summary>
        /// <param name="studentId">Initial value of the studentId property.</param>
        /// <param name="firstName">Initial value of the firstName property.</param>
        /// <param name="lastName">Initial value of the lastName property.</param>
        /// <param name="statusId">Initial value of the statusId property.</param>
        public static SATStudent CreateSATStudent(global::System.Int32 studentId, global::System.String firstName, global::System.String lastName, global::System.Int32 statusId)
        {
            SATStudent sATStudent = new SATStudent();
            sATStudent.studentId = studentId;
            sATStudent.firstName = firstName;
            sATStudent.lastName = lastName;
            sATStudent.statusId = statusId;
            return sATStudent;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 studentId
        {
            get
            {
                return _studentId;
            }
            set
            {
                if (_studentId != value)
                {
                    OnstudentIdChanging(value);
                    ReportPropertyChanging("studentId");
                    _studentId = StructuralObject.SetValidValue(value, "studentId");
                    ReportPropertyChanged("studentId");
                    OnstudentIdChanged();
                }
            }
        }
        private global::System.Int32 _studentId;
        partial void OnstudentIdChanging(global::System.Int32 value);
        partial void OnstudentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String firstName
        {
            get
            {
                return _firstName;
            }
            set
            {
                OnfirstNameChanging(value);
                ReportPropertyChanging("firstName");
                _firstName = StructuralObject.SetValidValue(value, false, "firstName");
                ReportPropertyChanged("firstName");
                OnfirstNameChanged();
            }
        }
        private global::System.String _firstName;
        partial void OnfirstNameChanging(global::System.String value);
        partial void OnfirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String lastName
        {
            get
            {
                return _lastName;
            }
            set
            {
                OnlastNameChanging(value);
                ReportPropertyChanging("lastName");
                _lastName = StructuralObject.SetValidValue(value, false, "lastName");
                ReportPropertyChanged("lastName");
                OnlastNameChanged();
            }
        }
        private global::System.String _lastName;
        partial void OnlastNameChanging(global::System.String value);
        partial void OnlastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String major
        {
            get
            {
                return _major;
            }
            set
            {
                OnmajorChanging(value);
                ReportPropertyChanging("major");
                _major = StructuralObject.SetValidValue(value, true, "major");
                ReportPropertyChanged("major");
                OnmajorChanged();
            }
        }
        private global::System.String _major;
        partial void OnmajorChanging(global::System.String value);
        partial void OnmajorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String classification
        {
            get
            {
                return _classification;
            }
            set
            {
                OnclassificationChanging(value);
                ReportPropertyChanging("classification");
                _classification = StructuralObject.SetValidValue(value, true, "classification");
                ReportPropertyChanged("classification");
                OnclassificationChanged();
            }
        }
        private global::System.String _classification;
        partial void OnclassificationChanging(global::System.String value);
        partial void OnclassificationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String address
        {
            get
            {
                return _address;
            }
            set
            {
                OnaddressChanging(value);
                ReportPropertyChanging("address");
                _address = StructuralObject.SetValidValue(value, true, "address");
                ReportPropertyChanged("address");
                OnaddressChanged();
            }
        }
        private global::System.String _address;
        partial void OnaddressChanging(global::System.String value);
        partial void OnaddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String city
        {
            get
            {
                return _city;
            }
            set
            {
                OncityChanging(value);
                ReportPropertyChanging("city");
                _city = StructuralObject.SetValidValue(value, true, "city");
                ReportPropertyChanged("city");
                OncityChanged();
            }
        }
        private global::System.String _city;
        partial void OncityChanging(global::System.String value);
        partial void OncityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String state
        {
            get
            {
                return _state;
            }
            set
            {
                OnstateChanging(value);
                ReportPropertyChanging("state");
                _state = StructuralObject.SetValidValue(value, true, "state");
                ReportPropertyChanged("state");
                OnstateChanged();
            }
        }
        private global::System.String _state;
        partial void OnstateChanging(global::System.String value);
        partial void OnstateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String zip
        {
            get
            {
                return _zip;
            }
            set
            {
                OnzipChanging(value);
                ReportPropertyChanging("zip");
                _zip = StructuralObject.SetValidValue(value, true, "zip");
                ReportPropertyChanged("zip");
                OnzipChanged();
            }
        }
        private global::System.String _zip;
        partial void OnzipChanging(global::System.String value);
        partial void OnzipChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String phone
        {
            get
            {
                return _phone;
            }
            set
            {
                OnphoneChanging(value);
                ReportPropertyChanging("phone");
                _phone = StructuralObject.SetValidValue(value, true, "phone");
                ReportPropertyChanged("phone");
                OnphoneChanged();
            }
        }
        private global::System.String _phone;
        partial void OnphoneChanging(global::System.String value);
        partial void OnphoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, true, "email");
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 statusId
        {
            get
            {
                return _statusId;
            }
            set
            {
                OnstatusIdChanging(value);
                ReportPropertyChanging("statusId");
                _statusId = StructuralObject.SetValidValue(value, "statusId");
                ReportPropertyChanged("statusId");
                OnstatusIdChanged();
            }
        }
        private global::System.Int32 _statusId;
        partial void OnstatusIdChanging(global::System.Int32 value);
        partial void OnstatusIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String pictureUrl
        {
            get
            {
                return _pictureUrl;
            }
            set
            {
                OnpictureUrlChanging(value);
                ReportPropertyChanging("pictureUrl");
                _pictureUrl = StructuralObject.SetValidValue(value, true, "pictureUrl");
                ReportPropertyChanged("pictureUrl");
                OnpictureUrlChanged();
            }
        }
        private global::System.String _pictureUrl;
        partial void OnpictureUrlChanging(global::System.String value);
        partial void OnpictureUrlChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SATModel", "FK_Enrollments_Students", "SATEnrollments")]
        public EntityCollection<SATEnrollment> SATEnrollments
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SATEnrollment>("SATModel.FK_Enrollments_Students", "SATEnrollments");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SATEnrollment>("SATModel.FK_Enrollments_Students", "SATEnrollments", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SATModel", "FK_Students_StudentStatus", "SATStudentStatuses")]
        public SATStudentStatus SATStudentStatus
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SATStudentStatus>("SATModel.FK_Students_StudentStatus", "SATStudentStatuses").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SATStudentStatus>("SATModel.FK_Students_StudentStatus", "SATStudentStatuses").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<SATStudentStatus> SATStudentStatusReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SATStudentStatus>("SATModel.FK_Students_StudentStatus", "SATStudentStatuses");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<SATStudentStatus>("SATModel.FK_Students_StudentStatus", "SATStudentStatuses", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SATModel", Name="SATStudentStatus")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SATStudentStatus : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SATStudentStatus object.
        /// </summary>
        /// <param name="sSID">Initial value of the SSID property.</param>
        /// <param name="sSName">Initial value of the SSName property.</param>
        public static SATStudentStatus CreateSATStudentStatus(global::System.Int32 sSID, global::System.String sSName)
        {
            SATStudentStatus sATStudentStatus = new SATStudentStatus();
            sATStudentStatus.SSID = sSID;
            sATStudentStatus.SSName = sSName;
            return sATStudentStatus;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SSID
        {
            get
            {
                return _SSID;
            }
            set
            {
                if (_SSID != value)
                {
                    OnSSIDChanging(value);
                    ReportPropertyChanging("SSID");
                    _SSID = StructuralObject.SetValidValue(value, "SSID");
                    ReportPropertyChanged("SSID");
                    OnSSIDChanged();
                }
            }
        }
        private global::System.Int32 _SSID;
        partial void OnSSIDChanging(global::System.Int32 value);
        partial void OnSSIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SSName
        {
            get
            {
                return _SSName;
            }
            set
            {
                OnSSNameChanging(value);
                ReportPropertyChanging("SSName");
                _SSName = StructuralObject.SetValidValue(value, false, "SSName");
                ReportPropertyChanged("SSName");
                OnSSNameChanged();
            }
        }
        private global::System.String _SSName;
        partial void OnSSNameChanging(global::System.String value);
        partial void OnSSNameChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SATModel", "FK_Students_StudentStatus", "SATStudents")]
        public EntityCollection<SATStudent> SATStudents
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SATStudent>("SATModel.FK_Students_StudentStatus", "SATStudents");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SATStudent>("SATModel.FK_Students_StudentStatus", "SATStudents", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
